# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'twitterClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for twitterClient
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'OAuthSwift', '~> 2.0.0'
#  pod 'OAuthSwiftAlamofire'

end
